### PR TITLE
Some changes to reduce allocation

### PR DESCRIPTION
**Pull request by samth**
Running `run.rkt` with no cache modifies them ~10x less often than any other
fields in the outer struct.

### CODE REVIEW

**Comment by samth** [comment]
This should copy the inner struct between 4-8k more times running `racket run.rkt`, while making the `expand-context` two fields smaller and not copying those fields at least 180k times.

I haven't measured total memory use changes though.

**Comment by samth** [comment]
Seems to save ~900k total allocation as measured by `racket -l gcstats -l racket`.

**Comment by samth** [comment]
However, it allocates about 150k _more_ for the same benchmark with `racket/base`. Maybe that indicates something interesting for further investigation, but I don't know if it should be merged.

**Comment by mflatt** [comment]
It makes sense that this change would be borderline if the fields are set 1/10 of the time. Removing 2 fields out of 16 (+ 3 words struct+GC overhead) would save about 2/19 in space. If that savings applies 90% of the time, and the other 10% is now twice as expensive (to allocate an inner and an outer layer), then the change would break even: (+ (* (/ 16 19) 9/10) 2/10) ≅ 1.

**Comment by samth** [comment]
Running `racket run.rkt` with no cache touches either field 6028 times, and neither field 385453 times, so that's about 1.5% of the time. 

Running `make run ARGS='-r -l typed/racket'`, it's about 2%.

**Comment by samth** [comment]
In both cases `binding-layer`, the next least-changed field, is about 10%.

**Comment by samth** [comment]
Unfortunately this merge went wrong and needs to be fixed.

**Comment by samth** [comment]
Ok, I fixed the merge issues, so review of this would be great.

**Comment by mflatt** [comment]
I've merged into my branch and expect to push later this morning.

**Pull request merged**
